// This file is auto-generated by AssetsPostprocessor.
// Do not modify this file manually.
//
// To regenerate this file manually, select the menu item Tools > LunarFramework > Generate R.cs.
//

using Luna;
using UnityEngine;

namespace R
{
    public static class Audios
    {
        public static Asset<AudioClip> タンホイザーとアイーダメドレー => new("Assets/Games/Common/Commend/Audios/タンホイザーとアイーダメドレー.mp3");
        public static Asset<AudioClip> ハレルヤ => new("Assets/Games/Common/Commend/Audios/ハレルヤ.mp3");
        public static Asset<AudioClip> 威風堂々 => new("Assets/Games/Common/Commend/Audios/威風堂々.mp3");
        public static Asset<AudioClip> 拍手 => new("Assets/Games/Common/Commend/Audios/拍手.mp3");
        public static Asset<AudioClip> 指笛 => new("Assets/Games/Common/Commend/Audios/指笛.mp3");
        public static Asset<AudioClip> 歓声 => new("Assets/Games/Common/Commend/Audios/歓声.mp3");
        public static Asset<AudioClip> 見よ勇者は帰る => new("Assets/Games/Common/Commend/Audios/見よ、勇者は帰る.mp3");
        public static Asset<AudioClip> BgmRouletteLoop => new("Assets/Games/Roulette/Audios/bgm_roulette_loop.mp3");
        public static Asset<AudioClip> SfxRouletteBack => new("Assets/Games/Roulette/Audios/sfx_roulette_back.mp3");
        public static Asset<AudioClip> SfxRouletteConfirm => new("Assets/Games/Roulette/Audios/sfx_roulette_confirm.mp3");
        public static Asset<AudioClip> SfxRouletteGameDecelerating => new("Assets/Games/Roulette/Audios/sfx_roulette_game_decelerating.mp3");
        public static Asset<AudioClip> SfxRouletteGameRotating => new("Assets/Games/Roulette/Audios/sfx_roulette_game_rotating.mp3");
        public static Asset<AudioClip> SfxRouletteSelect => new("Assets/Games/Roulette/Audios/sfx_roulette_select.mp3");
        public static AudioClip _10Sec => Resources.Load<AudioClip>("Audio/10sec");
        public static AudioClip _20Sec => Resources.Load<AudioClip>("Audio/20sec");
        public static AudioClip _30Sec => Resources.Load<AudioClip>("Audio/30sec");
        public static AudioClip EntryBgm => Resources.Load<AudioClip>("Audio/entry_bgm");
        public static AudioClip EntryKeySelect => Resources.Load<AudioClip>("Audio/entry_key_select");
        public static AudioClip High => Resources.Load<AudioClip>("Audio/high");
        public static AudioClip KeyBack => Resources.Load<AudioClip>("Audio/key_back");
        public static AudioClip KeyEffect => Resources.Load<AudioClip>("Audio/Key_effect");
        public static AudioClip KeyStart => Resources.Load<AudioClip>("Audio/key_start");
        public static AudioClip KeyTimer => Resources.Load<AudioClip>("Audio/key_timer");
        public static AudioClip Low => Resources.Load<AudioClip>("Audio/low");
        public static AudioClip SendPoker => Resources.Load<AudioClip>("Audio/send_poker");
        public static AudioClip TimerStart => Resources.Load<AudioClip>("Audio/timer_start");
        public static AudioClip Finish => Resources.Load<AudioClip>("HighAndLow/HightAndLowGame/Finish/Finish");

    }
}