// This file is auto-generated by AssetsPostprocessor.
// Do not modify this file manually.
//
// To regenerate this file manually, select the menu item Tools > LunarFramework > Generate R.cs.
//

using Luna;
using UnityEngine;

namespace R
{
    public static class Audios
    {
        public static Asset<AudioClip> SfxBack => new("Assets/Games/Common/Audios/sfx_back.mp3");
        public static Asset<AudioClip> SfxConfirm => new("Assets/Games/Common/Audios/sfx_confirm.mp3");
        public static Asset<AudioClip> SfxSelect => new("Assets/Games/Common/Audios/sfx_select.mp3");
        public static Asset<AudioClip> タンホイザーとアイーダメドレー => new("Assets/Games/Common/Commend/Audios/タンホイザーとアイーダメドレー.mp3");
        public static Asset<AudioClip> ハレルヤ => new("Assets/Games/Common/Commend/Audios/ハレルヤ.mp3");
        public static Asset<AudioClip> 威風堂々 => new("Assets/Games/Common/Commend/Audios/威風堂々.mp3");
        public static Asset<AudioClip> 拍手 => new("Assets/Games/Common/Commend/Audios/拍手.mp3");
        public static Asset<AudioClip> 指笛 => new("Assets/Games/Common/Commend/Audios/指笛.mp3");
        public static Asset<AudioClip> 歓声 => new("Assets/Games/Common/Commend/Audios/歓声.mp3");
        public static Asset<AudioClip> 見よ勇者は帰る => new("Assets/Games/Common/Commend/Audios/見よ、勇者は帰る.mp3");
        public static Asset<AudioClip> BgmHighLow => new("Assets/Games/High&Low/Audios/bgm_high&low.mp3");
        public static Asset<AudioClip> Sfx10Sec => new("Assets/Games/High&Low/Audios/sfx_10sec.mp3");
        public static Asset<AudioClip> Sfx20Sec => new("Assets/Games/High&Low/Audios/sfx_20sec.mp3");
        public static Asset<AudioClip> Sfx30Sec => new("Assets/Games/High&Low/Audios/sfx_30sec.mp3");
        public static Asset<AudioClip> SfxHigh => new("Assets/Games/High&Low/Audios/sfx_high.mp3");
        public static Asset<AudioClip> SfxLow => new("Assets/Games/High&Low/Audios/sfx_low.mp3");
        public static Asset<AudioClip> SfxSendPoker => new("Assets/Games/High&Low/Audios/sfx_send_poker.mp3");
        public static Asset<AudioClip> BgmRouletteLoop => new("Assets/Games/Roulette/Audios/bgm_roulette_loop.mp3");
        public static Asset<AudioClip> SfxRouletteGameDecelerating => new("Assets/Games/Roulette/Audios/sfx_roulette_game_decelerating.mp3");
        public static Asset<AudioClip> SfxRouletteGameRotating => new("Assets/Games/Roulette/Audios/sfx_roulette_game_rotating.mp3");
        public static AudioClip EntryKeySelect => Resources.Load<AudioClip>("Audio/entry_key_select");
        public static AudioClip KeyBack => Resources.Load<AudioClip>("Audio/key_back");
        public static AudioClip KeyEffect => Resources.Load<AudioClip>("Audio/Key_effect");
        public static AudioClip KeyStart => Resources.Load<AudioClip>("Audio/key_start");
        public static AudioClip KeyTimer => Resources.Load<AudioClip>("Audio/key_timer");
        public static AudioClip TimerStart => Resources.Load<AudioClip>("Audio/timer_start");
        public static AudioClip Finish => Resources.Load<AudioClip>("HighAndLow/HightAndLowGame/Finish/Finish");

    }
}